# Generated by Django 5.0.7 on 2024-07-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopitem_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ManyToManyField(to='shopitem_app.customer'),
        ),
    ]
